# Generated by Django 4.1.6 on 2023-02-16 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_variation_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variation',
            name='category',
        ),
    ]
